# Generated by Django 3.0.3 on 2020-05-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compolls', '0002_choice_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='voters',
            field=models.ManyToManyField(to='compolls.User'),
        ),
    ]
