# Generated by Django 3.0.3 on 2020-05-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidpolls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent1',
            name='parent1_phone',
            field=models.CharField(default='No Phone Number', max_length=20),
        ),
    ]
