# Generated by Django 3.0.3 on 2020-05-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidpolls', '0002_parent1_parent1_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child_date_return',
            field=models.DateField(blank=True, default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='child',
            name='child_return_asap',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parent1',
            name='parent1_phone',
            field=models.CharField(default='NO PHONE', max_length=20),
        ),
    ]
